---
kind: pipeline
type: docker
name: compliance

trigger:
  branch:
    include:
      - develop
      - main

steps:
  - name: lint-server
    image: node:lts
    commands:
      - cd server
      - npm ci
      - npm run lint
  - name: lint-console
    image: node:lts
    commands:
      - cd console
      - npm ci
      - npm run lint
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
      event:
        exclude:
          - pull_request

---
kind: pipeline
type: docker
name: testing-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    include:
      - develop
      - main

depends_on:
  - compliance

services:
  - name: mariadb
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: hub_backend

steps:
  - name: test-server-node-10
    image: node:10
    commands:
      - cd server
      - npm ci
      - npm test
  - name: test-server-node-12
    image: node:12
    commands:
      - cd server
      - npm ci
      - npm test
  - name: test-server-node-14
    image: node:14
    commands:
      - cd server
      - npm ci
      - npm test
  - name: test-server-node-16
    image: node:16
    commands:
      - cd server
      - npm ci
      - npm test
  - name: hubserver
    image: node:16
    detach: true
    commands:
      - cd server
      - 'echo ''{"mysql": "mysql://root:@mariadb:3306/hub_backend"}'' > config/local-production.json'
      - NODE_ENV=production npm start
  - name: test-api
    image: node:16
    commands:
      - cd test-api
      - npm ci
      - SERVER_URL=hubserver:3030 npm start
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
      event:
        exclude:
          - pull_request
---
kind: signature
hmac: dc109dd2902960d3ddbb9d96298a07b025464aaec38ad776072c99643be7a6bd

...
