---
kind: pipeline
type: docker
name: compliance

trigger:
  branch:
    include:
      - develop
      - main

steps:
  - name: lint-server
    image: node:16
    commands:
      - cd server
      - npm ci
      - npm run lint
  - name: lint-console
    image: node:16
    commands:
      - cd console
      - npm ci
      - npm run lint
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
      event:
        exclude:
          - pull_request

---
kind: pipeline
type: docker
name: testing-linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    include:
      - develop
      - main

depends_on:
  - compliance

steps:
  - name: test-server-node-12
    image: node:12
    commands:
      - cd server
      - npm ci --unsafe-perm
      - jest --runInBand --forceExit
  - name: test-server-node-14
    image: node:14
    commands:
      - cd server
      - npm ci --unsafe-perm
      - jest --runInBand --forceExit
  - name: test-server-node-16
    image: node:16
    environment:
      CC_TEST_REPORTER_ID:
        from_secret: cc_test_reporter_id
    commands:
      - cd server
      - npm ci
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - jest --runInBand --forceExit --coverage
      - ./scripts/report-code-coverage.sh
  - name: docker-testimage
    pull: always
    image: plugins/docker:latest
    settings:
      repo: registry.abrain.dev:5000/alarmdisplay/hub
      registry: registry.abrain.dev:5000
      tags: testing-amd64
    environment:
      DOCKER_PASSWORD:
        from_secret: tmpregistry_password
      DOCKER_USERNAME:
        from_secret: tmpregistry_username
    when:
      event:
        - push
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
      event:
        exclude:
          - pull_request
---
kind: pipeline
type: docker
name: docker-linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    include:
      - develop
      - main
  event:
    - push

depends_on:
  - testing-linux-amd64

services:
  - name: mariadb
    image: mariadb
    pull: if-not-exists
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: hub
  - name: sut
    image: registry.abrain.dev:5000/alarmdisplay/hub:testing-amd64
    pull: always
    environment:
      MYSQL_URI: mysql://root:@mariadb:3306/hub

steps:
  - name: test-api
    image: node:16
    commands:
      - cd test-api
      - npm ci
      - SERVER_URL=http://sut:3030 npm start
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
      event:
        exclude:
          - pull_request

image_pull_secrets:
  - dockerconfig
---
kind: signature
hmac: 165274b80b57e5f39fff4733ea57b4f26996f38e5b061295a5840d0b71199f91

...
