---
kind: pipeline
type: docker
name: compliance

trigger:
  branch:
    include:
      - develop
      - main

steps:
  - name: lint-server
    image: node:18.19.1
    commands:
      - cd server
      - npm ci
      - npm run lint
  - name: lint-console
    image: node:18.19.1
    commands:
      - cd console
      - npm ci
      - npm run lint

---
kind: pipeline
type: docker
name: testing-linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    include:
      - develop
      - main

depends_on:
  - compliance

steps:
  - name: test-server-node-16
    image: node:16.20.2
    commands:
      - cd server
      - npm ci
      - npx jest --runInBand --forceExit
  - name: test-server-node-18
    image: node:18.19.1
    environment:
      CC_TEST_REPORTER_ID:
        from_secret: cc_test_reporter_id
    commands:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - cd server
      - npm ci
      - npx jest --runInBand --forceExit --coverage
      - ../scripts/report-code-coverage.sh
---
kind: signature
hmac: bd0b981273fe7861e7c418d8cf0ab1dbba6890304592762ca6f5ccde305101db

...
